config/routes.rb
MyGists::Application.routes.draw do
  
  root :to => 'posts#index'
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/gists/mygists" => "gists#setmygists"
  get "/gists/allgists" => "gists#setallgists"
  resources :posts

  resources :gists

end

app/models/gist.rb
class Gist < ActiveRecord::Base
	validates :snippet, :lang, :presence => true
	 belongs_to :user

	
def self.search(search)
    if search 
        @local = User.where('name LIKE ?', "%#{search}%")
        return where(user_id: @local)
    else
        all
    end
end

def self.find_user(search)
    if search 
        find(:all, :conditions => ['user_id = ?', "#{search}"])
    else
        all
    end
end


end

app/models/post.rb
class Post < ActiveRecord::Base
	 belongs_to :user

	validates :content, :description, :presence => true


def timestamp
  created_at.strftime('%d %B %Y %H:%M:%S')
end

def self.search(search)
    if search 
        find(:all, :conditions => ['content  LIKE ?',"%#{search}%"])
    else
	all
    end
end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.nick = auth["info"]["nickname"]
      if(User.count == 0)
      	user.is_admin = true
      else
      	user.is_admin = false
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def is_user_logged?
  	unless !session[:user_id].nil?
  		redirect_to gists_path
  	end
  end

  def is_user_admin?
    unless !session[:user_id].nil? and current_user.is_admin
      redirect_to posts_path
    end
  end
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  before_filter :is_user_logged?, :except => [:index, :show, :search]
  before_filter :is_user_owner?, :only => [:edit, :destroy, :update]

  # GET /gists
  # GET /gists.json
  def index
    if(session[:user_id] && !session[:all_gists])
      @gists = Gist.order("created_at desc").find_user(session[:user_id])
    else
      @gists = Gist.order("created_at desc")
      if(!params[:desc].blank?)
        @gists = @gists.search(params[:desc]) 
        end
     end
    
   

    @gists = Kaminari.paginate_array(@gists).page(params[:page])# pagination
    # @gists = Gist.all
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(change_lang(gist_params))
    @gist.user = User.find(session[:user_id])

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(change_lang(gist_params))
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  def setmygists
   session[:all_gists] = false
   respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  def setallgists
    session[:all_gists] = true;
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end

    def not_allowed?(lang)
      allowed = Pygments.lexers.flatten.select.with_index{|a,i| (i+1) % 2 == 0}
      allowed = allowed.map{|a| a[:aliases][0]}
      allowed = allowed.delete_if{|a| (/-cpp/ =~ a || /-objc/ =~ a)}
      allowed = allowed.sort

      good_lang = false
      allowed.each do |a|

        if a == lang
          good_lang = true
          break
        end

      end

      !good_lang
    end

    def change_lang(gists)
     
      if not_allowed?(gists[:lang])
        gists[:lang] = "text"
      end

      return gists
    end

    def is_user_owner?

      if(@gist.user_id != session[:user_id])
        redirect_to gists_path
      end

    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :is_user_admin?, :except => [:index, :show, :search]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
 
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at desc") 
    
    if(!params[:desc].blank?)
      @posts = @posts.search(params[:desc]) 
    end

    @posts = Kaminari.paginate_array(@posts).page(params[:page]) # pagination
    # @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.find(session[:user_id])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :date, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create    
	auth = request.env["omniauth.auth"]
   	user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
   	session[:all_gists] = false
    session[:user_id] = user.id
   	redirect_to "/gists", :notice => "Signed in!"
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/gists/_form.html.erb
  <%= form_for(@gist) do |f| %>
  <%
  allowed = Pygments.lexers.flatten.select.with_index{|a,i| (i+1) % 2 == 0}
  allowed = allowed.map{|a| a[:aliases][0]}
  allowed = allowed.delete_if{|a| (/-cpp/ =~ a || /-objc/ =~ a)}
  allowed = allowed.sort
  %>
    <% if @gist.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

        <ul>
        <% @gist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :snippet %><br>
      <%= f.text_area :snippet, :size => "45x20",placeholder: 'Enter your code here...'  %>
    </div>
    <div class="field">
      <%= f.label :lang %><br>
      <%= f.select :lang, allowed %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/gists/_gist.html.erb
<div class="col-sm-6 col-md-4">
	<div class="thumbnail">
		<div class="caption">

			  <%= raw Pygments.highlight(gist.snippet.length > 15 ? gist.snippet[0,15] + "..." : gist.snippet, lexer: gist.lang) %>
			  <p>Language: <%= gist.lang %></p>
			  <p>Description: <%= gist.description %></p>
			  
			   <%- if(session[:user_id] and gist.user_id == session[:user_id])  %>
                                  <%= link_to 'Show', gist, :class => 'btn btn-success' %>
				  <%= link_to 'Edit', edit_gist_path(gist), :class => 'btn btn-warning' %>
				  <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
			  <%- else %>
                                  <%= link_to 'Show', gist, :class => 'btn btn-success btn-block' %>
                          <%- end %>
		</div>
	</div>
</div>

app/views/gists/edit.html.erb
<div class="container">
    <div class="page-header">
        <h1>Editing gist</h1>
    </div>

    <%= render 'form' %>

    <%= link_to 'Show', @gist, :class => 'btn btn-success' %> 
    <%= link_to 'Back', gists_path, :class => 'btn btn-primary' %>
</div>

app/views/gists/index.html.erb
<div class="container">
    <div class="page-header">
        <h1>Listing gists</h1>
         <%- if(session[:user_id])  %>
           <%- if(!session[:all_gists])  %>
             <%= link_to 'My gists', "/gists/mygists", :class => 'btn btn-default actual' %>
             <%= link_to 'All gists', "/gists/allgists", :class => 'btn btn-default' %>
            <%- else %>  
              <%= link_to 'My gists',"/gists/mygists", :class => 'btn btn-default' %>
              <%= link_to 'All gists', "/gists/allgists", :class => 'btn btn-default  actual' %>        
           <%- end %>
          <%- end %>
    </div>

   <%- if(session[:user_id])  %>
       <%= link_to 'New Gist', new_gist_path, :class => 'btn btn-default' %>
       <br><br/>
   <%- end %>

    <div class="row2">
        <%= render @gists %>
    </div>
    <%= paginate @gists, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/gists/index.js.erb
$(".row2").append("<div class='row2'><%= escape_javascript(render(@gists)) %></div>");

app/views/gists/new.html.erb
<div class="container">
	<div class="page-header">
	    <h1>New gist</h1>
	</div>

    <%= render 'form' %>

    <%= link_to 'Back', gists_path, :class => 'btn btn-primary' %>
</div>

app/views/gists/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Snippet:</strong>
  <%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @gist.lang %>
</p>
<p>
  <strong>Description:</strong>
  <%= @gist.description %>
</p>


<p>
  <strong>User:</strong>
  <%- if(@gist.user) %>
  <%- if(!@gist.user.name.blank?) %>
  	<%=  @gist.user.name %>
	<%- else %>
	<%=  @gist.user.nick %>
  <%- end else %>
  		Not specified
  <%- end %>
</p>
<%- if(@current_user)  %>
  <%= link_to 'Edit', edit_gist_path(@gist), :class => 'btn btn-warning' %> 
<%- end %>
<%= link_to 'Back', gists_path, :class => 'btn btn-info' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts"><span class="glyphicon glyphicon-home"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/gists">Gists</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group" data-toggle="tooltip" title="Search">
          <%= text_field_tag :desc, params[:desc],  :class => 'form-control' %>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%- if(current_user)  %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=  current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Sign out", "/signout" %></li>          
          </ul>
          </li>
        <%- else  %>
          <li class="active"><%= link_to "Sign in with Github", "/auth/github" %></li>
        <%- end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :size => "45x20",placeholder: 'Write something here...'  %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, size:25 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, size: 25, maxlength: 50 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-sm-12 col-md-12">
	<div class="thumbnail">
		<div class="caption">
		  <h3><%= link_to post.description, post_path(post) %></h3>
		 
		  <small><em><%= post.timestamp %></em></small>
		 
		  <p><%= truncate(strip_tags(post.content), length: 600) %></p>
		  <%- if(session[:user_id] and User.find(session[:user_id]).is_admin) %>
			  <%= link_to 'Show', post, :class => 'btn btn-success' %>
			  <%= link_to 'Edit', edit_post_path(post), :class => 'btn btn-warning' %>
			  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
		  <%- end %>
	  </div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
    <div class="page-header">    
        <h1>Editing post</h1>
    </div>

    <%= render 'form' %>

    <%= link_to 'Show', @post, :class => 'btn btn-success' %> 
    <%= link_to 'Back', posts_path, :class => 'btn btn-primary' %>
</div>

app/views/posts/index.html.erb
<div class="container">
    <div class="page-header">
        <h1>Posts</h1>
    </div>
   
    <%- if(session[:user_id] && User.find(session[:user_id]).is_admin)  %>
        <%= link_to 'New Post', new_post_path, :class => 'btn btn-default' %>
        <br><br/>
    <%- end %>

    <div class="row">
    	<%= render @posts %>
    </div>
    <%= paginate @posts, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/posts/index.js.erb
$(".row").append("<div class='row'><%= escape_javascript(render(@posts)) %></div>");

app/views/posts/new.html.erb
<div class="container">
	<div class="page-header">  
	    <h1>New post</h1>
	</div>


    <%= render 'form' %>

    <%= link_to 'Back', posts_path, :class => 'btn btn-primary' %>
</div>

app/views/posts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <h1>
  <%= @post.description %>
  </h1>
  <%= @post.timestamp %><br/>
  <strong>By:</strong>
  <%- if(@post.user) %>
  <%- if(!@post.user.name.blank?) %>
    <%=  @post.user.name %>
  <%- else %>
    <%=  @post.user.nick %>
  <%- end else %>
      Not specified
  <%- end %>
  <hr/>
</p>

<p style='font-size: 18px;'>
  
  <%= @post.content %>
</p>


<br> 
    <%- if(session[:user_id] && User.find(session[:user_id]).is_admin)  %>
    <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-warning' %>
     <%- end %>
    <%= link_to 'Back', posts_path, :class => 'btn btn-primary' %>
</div>